### ISSUE TITLE
Multiplayer file upload doesn't show ready for opponent

### ISSUE THREAD

**Issue by Terryaki** [tz-hmc/auto-chart-js#1]
If two people on separate networks open the same room (indicated by the 4 letter code after the demo site), both are greeted a file upload.

One person uploads and gets "ready".

The second person's UI is never updated and all they see is the file upload UI.

**Comment by tz-hmc** [comment]
There was an issue causing the container to fail (an AWS platform predeploy script was not exiting with 0) which has been recently fixed
